name: Test status event triggers a workflow
on: status

jobs:
  test_danger_on_status:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DANGER_GITHUB_API_BASE_URL: 'https://api.github.com'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node_version: 10.x

      - name: Install Yarn
        run: npm install -g yarn

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node_modules

      - name: Yarn Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        # frozen-lockfile will make the build fail if the lockfile is not there
        run: yarn install --frozen-lockfile

      - name: ⚠️ Danger
        run: |
          yarn run danger ci --dangerfile dangerfiles/dump_context.ts --id danger_from_status
